### ISSUE TITLE
DateTimePicker Update

### ISSUE THREAD

**Issue by ChasDouglass** [edvin/tornadofx-controls#7]
I am using the DateTimePicker control allowing both user entry directly into the control, and an "injected" value based on a menu selection.  When the menu selection sets the "dateTimeValue" the display is only updated (apparently) if the date changes.  If just the time changes, the control does not show the change.

For instance, if the control is currently showing "06/30/2017 12:15" and my menu item sets "dateTimeValue" to LocalDateTime().now() then the field will not show the change all day on 6/30.  If I set a LocalDateTime where the date is different into dateTimeValue then the field updates correctly.

**Comment by edvin** [comment]
Thanks for reporting. I have committed a fix for it now. Can you check if this resolves the issue for you?

**Comment by ChasDouglass** [comment]
Thanks, this does fix the problem.

**Comment by edvin** [comment]
Great! Can you use the snapshot in your project for now or do you need a release?

**Comment by ChasDouglass** [comment]
I'm fine using the snapshot I made locally, thanks!

**Comment by edvin** [comment]
Perfect! Thanks for getting back to me.
