### ISSUE TITLE
DateTimePicker large format shortened

### ISSUE THREAD

**Issue by DJViking** [edvin/tornadofx-controls#9]
When using a large format the control doesn't grow large enough to show the entire DateTime.
Using the format yyyy-MM-dd'T'HH:mm:ss.SSS.

**Comment by edvin** [comment]
I've added a function that will align the prefColumnCount with the current format. You can try to add the following code after you have set the format to see the effect until the next release:

```kotlin
picker.getEditor().setPrefColumnCount(picker.getFormat().length());
 ```

Does that work for you?

**Comment by DJViking** [comment]
That worked perfectly

**Comment by edvin** [comment]
Great :) Thanks for getting back to me.
